### ISSUE TITLE
Use promisified modals with headlessui

### ISSUE THREAD

**Issue by mrhighstone** [AndrewBastin/vue-promise-modals#1]
I'm excited about your promisified modal solution and thinking of getting this to work with [Headlessui](https://headlessui.com/v1/vue/dialog). Especially the modal and drawer components. Would you think this is possible? 

Is the ModalSystem tied to a specific implementation? How does the openModel know what modal (eg a modal or drawer component) to open?

**Comment by AndrewBastin** [comment]
@mrhighstone I am not sure about the drawer (this library isn't specifically made for this use case for the most part).

The [demo site](https://vue-promise-modals.andrewbast.in) code is also present in this repo, see https://github.com/AndrewBastin/vue-promise-modals/tree/main/demo/src/components/example for reference implementations. When you call `openModal` it renders the component passed to it, so you can just give in your dialog component and it should be fine.

I don't see why it shouldn't work with the Headless UI dialog components

**Comment by mrhighstone** [comment]
Just wanted to let you that I managed to get it to work. Both the modal and drawer.

Many thanks for the good work, saves me a lot of hassle in opening, closing and evaluating the results!
